import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client.ts";
import { PrismaNeon } from "@prisma/adapter-neon";

const adapter = new PrismaNeon({
  connectionString: process.env.DATABASE_URL,
});
const prisma = new PrismaClient({ adapter });

const brands = [
  { slug: "norev", name: "Norev" },
  { slug: "gt-spirit", name: "GT Spirit" },
  { slug: "minichamps", name: "Minichamps" },
  { slug: "otto", name: "Otto Mobile" },
  { slug: "ixo", name: "IXO" },
  { slug: "mcg", name: "MCG" },
  { slug: "che-zhi", name: "Che Zhi" },
  { slug: "bburago", name: "Bburago" },
  { slug: "maisto", name: "Maisto" },
  { slug: "accessory", name: "Phụ kiện" },
];

const IMG = {
  bugatti: "/images/products/bugatti-atlantic.jpg",
  mercedes: "/images/products/mercedes-amg-gtr.jpg",
  bentley: "/images/products/bentley-continental.jpg",
  astonMartin: "/images/products/aston-martin-dbs.jpg",
  fordGt: "/images/products/ford-gt.jpg",
};

const scales = [
  { slug: "1-12", label: "1:12" },
  { slug: "1-18", label: "1:18" },
  { slug: "1-24", label: "1:24" },
  { slug: "1-32", label: "1:32" },
  { slug: "1-43", label: "1:43" },
];

const products = [
  {
    slug: "bmw-m4-white-1-18",
    nameEn: "BMW M4 Competition White 1:18",
    nameVi: "BMW M4 Competition Trắng 1:18",
    priceUsd: 129.0,
    compareAtUsd: null,
    imageColor: "#e5e7eb",
    carBrand: "BMW",
    bodyStyle: "coupe",
    badge: "NEW",
    brand: "norev",
    scale: "1-18",
    isNewArrival: true,
    isBestSeller: true,
  },
  {
    slug: "porsche-911-silver-1-18",
    nameEn: "Porsche 911 Turbo Silver 1:18",
    nameVi: "Porsche 911 Turbo Bạc 1:18",
    priceUsd: 149.0,
    compareAtUsd: 159.0,
    imageColor: "#9ca3af",
    carBrand: "Porsche",
    bodyStyle: "sports",
    badge: null,
    brand: "minichamps",
    scale: "1-18",
    isNewArrival: true,
    isBestSeller: true,
  },
  {
    slug: "mercedes-300sl-red-1-18",
    nameEn: "Mercedes-Benz 300SL Red 1:18",
    nameVi: "Mercedes-Benz 300SL Đỏ 1:18",
    priceUsd: 189.0,
    compareAtUsd: null,
    imageColor: "#dc2626",
    carBrand: "Mercedes-Benz",
    bodyStyle: "sports",
    badge: "HOT",
    brand: "otto",
    scale: "1-18",
    isNewArrival: true,
  },
  {
    slug: "mini-cooper-blue-1-24",
    nameEn: "Mini Cooper S Blazing Blue 1:24",
    nameVi: "Mini Cooper S Xanh Rực 1:24",
    priceUsd: 79.67,
    compareAtUsd: 83.74,
    imageColor: "#1e3a8a",
    carBrand: "Mini",
    bodyStyle: "hatchback",
    badge: "-5%",
    brand: "otto",
    scale: "1-24",
    isPreOrder: true,
  },
  {
    slug: "mclaren-gts-red-1-18",
    nameEn: "McLaren GTS Red 1:18",
    nameVi: "McLaren GTS Đỏ 1:18",
    priceUsd: 88.62,
    compareAtUsd: 92.68,
    imageColor: "#b91c1c",
    carBrand: "McLaren",
    bodyStyle: "sports",
    badge: "-4%",
    brand: "gt-spirit",
    scale: "1-18",
    isPreOrder: true,
    isBestSeller: true,
  },
  {
    slug: "bmw-m5-grey-1-18",
    nameEn: "BMW M5 CS Brands Hatch Grey 1:18",
    nameVi: "BMW M5 CS Xám Brands Hatch 1:18",
    priceUsd: 88.62,
    compareAtUsd: 92.68,
    imageColor: "#4b5563",
    carBrand: "BMW",
    bodyStyle: "sedan",
    badge: "-4%",
    brand: "gt-spirit",
    scale: "1-18",
    isPreOrder: true,
  },
  {
    slug: "vw-golf-gti-red-1-18",
    nameEn: "Volkswagen Golf GTI Mk2 Red 1:18",
    nameVi: "Volkswagen Golf GTI Mk2 Đỏ 1:18",
    priceUsd: 106.5,
    compareAtUsd: null,
    imageColor: "#dc2626",
    carBrand: "Volkswagen",
    bodyStyle: "hatchback",
    badge: "BACK IN STOCK",
    brand: "norev",
    scale: "1-18",
    isBestSeller: true,
  },
  {
    slug: "vw-golf-gti-black-1-18",
    nameEn: "Volkswagen Golf GTI Mk6 Black 1:18",
    nameVi: "Volkswagen Golf GTI Mk6 Đen 1:18",
    priceUsd: 97.56,
    compareAtUsd: null,
    imageColor: "#111827",
    carBrand: "Volkswagen",
    bodyStyle: "hatchback",
    badge: "LAST ONE",
    brand: "norev",
    scale: "1-18",
  },
  {
    slug: "porsche-911-rwb-silver-1-18",
    nameEn: "Porsche 911 997 RWB Silver 1:18",
    nameVi: "Porsche 911 997 RWB Bạc 1:18",
    priceUsd: 55.28,
    compareAtUsd: null,
    imageColor: "#d1d5db",
    carBrand: "Porsche",
    bodyStyle: "sports",
    badge: null,
    brand: "ixo",
    scale: "1-18",
  },
  {
    slug: "mercedes-500e-black-1-18",
    nameEn: "Mercedes 500E W124 Black 1:18",
    nameVi: "Mercedes 500E W124 Đen 1:18",
    priceUsd: 184.55,
    compareAtUsd: null,
    imageColor: "#0f172a",
    carBrand: "Mercedes-Benz",
    bodyStyle: "sedan",
    badge: null,
    brand: "norev",
    scale: "1-18",
  },
  {
    slug: "chevrolet-caprice-police-1-18",
    nameEn: "Chevrolet Caprice Police Car 1:18",
    nameVi: "Chevrolet Caprice Xe Cảnh Sát 1:18",
    priceUsd: 57.72,
    compareAtUsd: null,
    imageColor: "#1d4ed8",
    carBrand: "Chevrolet",
    bodyStyle: "sedan",
    badge: "LAST ONE",
    brand: "mcg",
    scale: "1-18",
  },
  {
    slug: "bugatti-atlantic-silver-1-24",
    nameEn: "Bugatti Atlantic Silver/Blue 1:24",
    nameVi: "Bugatti Atlantic Bạc/Xanh 1:24",
    priceUsd: 45.9,
    compareAtUsd: null,
    imageColor: "#9ca3af",
    carBrand: "Bugatti",
    bodyStyle: "sports",
    imageUrl: IMG.bugatti,
    badge: "NEW",
    brand: "che-zhi",
    scale: "1-24",
    isNewArrival: true,
    isBestSeller: true,
  },
  {
    slug: "bugatti-atlantic-luggage-set-1-24",
    nameEn: "Bugatti Atlantic 1:24 (with luggage set)",
    nameVi: "Bugatti Atlantic 1:24 (tặng kèm vali)",
    priceUsd: 49.9,
    compareAtUsd: 54.9,
    imageColor: "#9ca3af",
    carBrand: "Bugatti",
    bodyStyle: "sports",
    imageUrl: IMG.bugatti,
    badge: "-9%",
    brand: "che-zhi",
    scale: "1-24",
    isPreOrder: true,
  },
  {
    slug: "mercedes-amg-gtr-green-1-24",
    nameEn: "Mercedes-AMG GT R Green 1:24",
    nameVi: "Mercedes-AMG GT R Xanh Lá 1:24",
    priceUsd: 42.5,
    compareAtUsd: null,
    imageColor: "#16a34a",
    carBrand: "Mercedes-Benz",
    bodyStyle: "sports",
    imageUrl: IMG.mercedes,
    badge: "NEW",
    brand: "che-zhi",
    scale: "1-24",
    isNewArrival: true,
    isBestSeller: true,
  },
  {
    slug: "mercedes-amg-gtr-preorder-1-24",
    nameEn: "Mercedes-AMG GT R Green 1:24 (V8 Turbo edition)",
    nameVi: "Mercedes-AMG GT R Xanh Lá 1:24 (bản V8 Turbo)",
    priceUsd: 46.9,
    compareAtUsd: 49.9,
    imageColor: "#16a34a",
    carBrand: "Mercedes-Benz",
    bodyStyle: "sports",
    imageUrl: IMG.mercedes,
    badge: "-6%",
    brand: "che-zhi",
    scale: "1-24",
    isPreOrder: true,
  },
  {
    slug: "bentley-continental-green-1-24",
    nameEn: "Bentley Continental GT Green 1:24",
    nameVi: "Bentley Continental GT Xanh Lá 1:24",
    priceUsd: 47.9,
    compareAtUsd: null,
    imageColor: "#166534",
    carBrand: "Bentley",
    bodyStyle: "coupe",
    imageUrl: IMG.bentley,
    badge: "NEW",
    brand: "che-zhi",
    scale: "1-24",
    isNewArrival: true,
  },
  {
    slug: "bentley-continental-preorder-1-24",
    nameEn: "Bentley Continental GT Green 1:24 (limited)",
    nameVi: "Bentley Continental GT Xanh Lá 1:24 (bản giới hạn)",
    priceUsd: 52.9,
    compareAtUsd: 57.9,
    imageColor: "#166534",
    carBrand: "Bentley",
    bodyStyle: "coupe",
    imageUrl: IMG.bentley,
    badge: "-9%",
    brand: "che-zhi",
    scale: "1-24",
    isPreOrder: true,
  },
  {
    slug: "aston-martin-dbs-gold-1-24",
    nameEn: "Aston Martin DBS Pearl Gold 1:24",
    nameVi: "Aston Martin DBS Vàng Ánh Ngọc 1:24",
    priceUsd: 44.5,
    compareAtUsd: null,
    imageColor: "#ca8a04",
    carBrand: "Aston Martin",
    bodyStyle: "coupe",
    imageUrl: IMG.astonMartin,
    badge: "NEW",
    brand: "che-zhi",
    scale: "1-24",
    isNewArrival: true,
    isBestSeller: true,
  },
  {
    slug: "ford-gt-yellow-1-24",
    nameEn: "Ford GT Yellow/Black Stripe 1:24",
    nameVi: "Ford GT Vàng Sọc Đen 1:24",
    priceUsd: 43.9,
    compareAtUsd: null,
    imageColor: "#eab308",
    carBrand: "Ford",
    bodyStyle: "sports",
    imageUrl: IMG.fordGt,
    badge: "NEW",
    brand: "che-zhi",
    scale: "1-24",
    isNewArrival: true,
  },
  {
    slug: "ford-gt-preorder-1-24",
    nameEn: "Ford GT Yellow/Black Stripe 1:24 (light & sound)",
    nameVi: "Ford GT Vàng Sọc Đen 1:24 (có đèn & âm thanh)",
    priceUsd: 48.9,
    compareAtUsd: 52.9,
    imageColor: "#eab308",
    carBrand: "Ford",
    bodyStyle: "sports",
    imageUrl: IMG.fordGt,
    badge: "-8%",
    brand: "che-zhi",
    scale: "1-24",
    isPreOrder: true,
  },
];

const accessories = [
  {
    slug: "figure-mechanic-1-18",
    nameEn: "Mechanic Figure 1:18",
    nameVi: "Mô hình nhân vật thợ máy 1:18",
    priceUsd: 8.9,
    compareAtUsd: null,
    imageColor: "#57534e",
    badge: "NEW",
    brand: "accessory",
    scale: "1-18",
    category: "accessory",
  },
  {
    slug: "figure-racer-1-18",
    nameEn: "Racing Driver Figure 1:18",
    nameVi: "Mô hình nhân vật tay đua 1:18",
    priceUsd: 8.9,
    compareAtUsd: null,
    imageColor: "#1d4ed8",
    badge: null,
    brand: "accessory",
    scale: "1-18",
    category: "accessory",
  },
  {
    slug: "diorama-gas-station-1-18",
    nameEn: "Gas Station Diorama Set 1:18",
    nameVi: "Bộ tiểu cảnh trạm xăng trang trí 1:18",
    priceUsd: 24.9,
    compareAtUsd: 27.9,
    imageColor: "#dc2626",
    badge: "-11%",
    brand: "accessory",
    scale: "1-18",
    category: "accessory",
  },
  {
    slug: "diorama-tools-1-18",
    nameEn: "Garage Tool Set Diorama 1:18",
    nameVi: "Bộ dụng cụ garage trang trí 1:18",
    priceUsd: 15.9,
    compareAtUsd: null,
    imageColor: "#78716c",
    badge: null,
    brand: "accessory",
    scale: "1-18",
    category: "accessory",
  },
  {
    slug: "mika-display-box-1-18",
    nameEn: "Mika Display Case (1:18)",
    nameVi: "Hộp mika trưng bày mô hình tỉ lệ 1:18",
    priceUsd: 12.9,
    compareAtUsd: null,
    imageColor: "#e5e7eb",
    badge: "NEW",
    brand: "accessory",
    scale: "1-18",
    category: "accessory",
  },
  {
    slug: "mika-display-box-1-24",
    nameEn: "Mika Display Case (1:24)",
    nameVi: "Hộp mika trưng bày mô hình tỉ lệ 1:24",
    priceUsd: 9.9,
    compareAtUsd: null,
    imageColor: "#e5e7eb",
    badge: null,
    brand: "accessory",
    scale: "1-24",
    category: "accessory",
  },
];

async function main() {
  console.log("Seeding brands...");
  const brandMap = {};
  for (const b of brands) {
    const created = await prisma.brand.upsert({
      where: { slug: b.slug },
      update: {},
      create: b,
    });
    brandMap[b.slug] = created.id;
  }

  console.log("Seeding scales...");
  const scaleMap = {};
  for (const s of scales) {
    const created = await prisma.scale.upsert({
      where: { slug: s.slug },
      update: {},
      create: s,
    });
    scaleMap[s.slug] = created.id;
  }

  console.log("Seeding products...");
  const imagePool = Object.values(IMG);
  const allProducts = products.concat(accessories);
  for (const [index, p] of allProducts.entries()) {
    const { brand, scale, ...rest } = p;
    const imageUrl = rest.imageUrl ?? (rest.category === "accessory" ? null : imagePool[index % imagePool.length]);
    await prisma.product.upsert({
      where: { slug: p.slug },
      update: {
        imageUrl,
        category: rest.category ?? "car",
        carBrand: rest.carBrand ?? null,
        bodyStyle: rest.bodyStyle ?? null,
        isBestSeller: rest.isBestSeller ?? false,
      },
      create: {
        ...rest,
        imageUrl,
        brandId: brandMap[brand],
        scaleId: scaleMap[scale],
      },
    });
  }

  console.log("Seed complete.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
